### ISSUE TITLE
TypeError: Cannot read property '*' of null

### ISSUE THREAD

**Issue by stewartanderson3** [stewie1570/leaf-validator#106]
Example of failure:
```js
it("can add data to a null value in an object", () => {
    const orig = {
        level1: {
            level2: null
        }
    };
    expect(set("level1.level2.level3.level4")
        .to("value")
        .in(orig))
        .toEqual({
            level1: {
                level2: { level3: { level4: "value" } }
            }
        });
});
```

Error:
```
TypeError: Cannot read property 'level3' of null

      56 |     return target === "" || obj === undefined ? obj
      57 |         : firstDotIndex === -1
    > 58 |             ? obj[target]
         |                  ^
      59 |             : get(target.substring(firstDotIndex + 1)).from(obj[childLocation]);    
      60 | }
      61 | 

      at getValueFrom (src/lib/domain.ts:58:18)
      at Object.from (src/lib/domain.ts:63:28)
      at getValueFrom (src/lib/domain.ts:59:56)
      at Object.from (src/lib/domain.ts:63:28)
      at getValueFrom (src/lib/domain.ts:59:56)
      at Object.from (src/lib/domain.ts:63:28)
      at getModelProgressionFrom (src/lib/domain.ts:41:41)
      at Object.in (src/lib/domain.ts:68:31)
      at Object.<anonymous> (src/lib/domain.test.ts:292:16)
```

**Comment by stewartanderson3** [comment]
v5.2.4
